### ISSUE TITLE
pip install PyObjC error

### ISSUE THREAD

**Issue by NikQATech** [bradtraversy/alexis_speech_assistant#11]
Error while installing. How can i fix it?

C:\Users\USER\AppData\Local\Programs\Python\Python38-32\Scripts>pip install PyObjC
Collecting PyObjC
  Using cached pyobjc-6.1-py3-none-any.whl (2.9 kB)
Collecting pyobjc-framework-NetFS==6.1; platform_release >= "10.0"
  Downloading pyobjc_framework_NetFS-6.1-py2.py3-none-any.whl (3.8 kB)
Collecting pyobjc-framework-AddressBook==6.1
  Downloading pyobjc-framework-AddressBook-6.1.tar.gz (76 kB)
     |████████████████████████████████| 76 kB 732 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\USER\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-p5hd7qla\\pyobjc-framework-AddressBook\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-p5hd7qla\\pyobjc-framework-AddressBook\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-install-p5hd7qla\pyobjc-framework-AddressBook\pip-egg-info'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-p5hd7qla\pyobjc-framework-AddressBook\
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-p5hd7qla\pyobjc-framework-AddressBook\setup.py", line 22, in <module>
        Extension(
      File "C:\Users\USER\AppData\Local\Temp\pip-install-p5hd7qla\pyobjc-framework-AddressBook\pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "C:\Users\USER\AppData\Local\Temp\pip-install-p5hd7qla\pyobjc-framework-AddressBook\pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "c:\users\USER\appdata\local\programs\python\python38-32\lib\plistlib.py", line 99, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "c:\users\USER\appdata\local\programs\python\python38-32\lib\contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "c:\users\USER\appdata\local\programs\python\python38-32\lib\plistlib.py", line 82, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ProDeSquare** [comment]
Hey, @imnotadeveloper this issue was opened 29 days ago and no problem if you've already found the solution. Someone in the future may benefit from this.

Package **PyObjC** is only required and for **MacOS** & **OSX** based environments. As on Windows/Linux the package isn't required.

**Comment by chetjones003** [comment]
@ProDeSquare I definitely didn't know that. That helps a lot. Thanks

**Comment by Dergarcon** [comment]
I just rebooted the system to solve the problem.
